simCommInc <- function(dataCaseImportNotified, dataIncImport, dataSpilloverOffspring, dataSpilloverDateIsolate, 
                       currentParam, distGen, distIsolate, distTravel){
  
  startTimePeriod = currentParam$startTimePeriod
  endTimePeriod   = currentParam$endTimePeriod
  nameParam       = colnames(currentParam$param)
  
  dataCaseImportMissed = data.table(NOTIFIED = 'N',
                                    DATE_ARRIVAL = currentParam$time,
                                    SOURCE_OF_INFECTION = 1,
                                    LOCAL_OVERSEAS = 1,
                                    CASE_COUNT = currentParam$param[4]*dataIncImport[, SPLINE])

  dataCaseImport = rbindlist(list(dataCaseImportNotified, dataCaseImportMissed),
                             use.names = TRUE,
                             fill = TRUE)
  
  dataCaseImport = dataCaseImport[CASE_COUNT != 0,]
  
  if(dataCaseImport[,.N] != 0){
  # determine no. of offsprings generated by notified imported cases from arrival to isolation
  # determine no. of offsprings generated by missed imported cases from arrival to end of infectiousness
  dataCaseImport[NOTIFIED == 'Y', DURATION_AT_LARGE := DATE_ISOLATE_FROM_COMM - DATE_ARRIVAL + 1]
  dataCaseImport[NOTIFIED == 'N', DURATION_AT_LARGE := 31]

  dataCaseImport = dataCaseImport[, c('NOTIFIED', 'DATE_ARRIVAL', 'DURATION_AT_LARGE', 'CASE_COUNT')]
  dataCaseImport = dataCaseImport[rep(seq_len(nrow(dataCaseImport)), each = 14), ]
  dataCaseImport[, `:=` (DATE_INFECTION = DATE_ARRIVAL + rep(distTravel[, DAY], times = .N/14),
                         PROB_INFECTION = rep(distTravel[, PROB_INFECTION], times = .N/14))] #PROB_INFECTION on the respective days prior to arrival

  seqDayAtLarge = dataCaseImport[, DURATION_AT_LARGE]
  seqDayAtLarge = unlist(sapply(1:length(seqDayAtLarge), function(x){ seq_len(seqDayAtLarge[x]) })) - 1

  dataCaseImport = dataCaseImport[rep(seq_len(dataCaseImport[,.N]), DURATION_AT_LARGE),]

  dataCaseImport[, DATE_AT_LARGE := DATE_ARRIVAL + seqDayAtLarge]
  dataCaseImport[, DAY_SINCE_INFECTION := DATE_AT_LARGE - DATE_INFECTION]

  # remove data if day since infection more than 21 days
  dataCaseImport = dataCaseImport[DAY_SINCE_INFECTION<=21]

  dataCaseImport = merge(dataCaseImport, distGen, by.x = 'DAY_SINCE_INFECTION', by.y = 'DAY', all.x = T)

  # determine number of offspring generated by respective cases over respective days
  dataCaseImport[, OFFSPRING := CASE_COUNT*PROB_INFECTION*GEN_INTERVAL*currentParam$param[1]]

  dataCaseImport = dataCaseImport[, sum(OFFSPRING), by = .(DATE_AT_LARGE, NOTIFIED)]
  setnames(dataCaseImport, c('DAY_OF_INFECTION', 'NOTIFIED_INFECTOR', 'OFFSPRING'))
  
  # add spillover import offspring
  # dataCaseImport = data.table() # for period 3 only
  dataCaseImport = rbind(dataCaseImport, dataSpilloverOffspring)
  }else{
    dataCaseImport = dataSpilloverOffspring
  }
  
  

  dataCaseImport[NOTIFIED_INFECTOR =="Y" & DAY_OF_INFECTION >= startTimePeriod & DAY_OF_INFECTION <= endTimePeriod,
                 `:=` (NOTIFIED_OFFSPRING_NOTIFIED_INFECTOR = OFFSPRING*currentParam$param[2],
                       MISSED_OFFSPRING_NOTIFIED_INFECTOR   = OFFSPRING*(1-currentParam$param[2]))]

  dataCaseImport[NOTIFIED_INFECTOR =="N" & DAY_OF_INFECTION >= startTimePeriod & DAY_OF_INFECTION <= endTimePeriod,
                 `:=` (NOTIFIED_OFFSPRING_MISSED_INFECTOR = OFFSPRING*currentParam$param[3],
                       MISSED_OFFSPRING_MISSED_INFECTOR   = OFFSPRING*(1-currentParam$param[3]))]

  #setorder(dataCaseImport, -NOTIFIED_INFECTOR, DAY_OF_INFECTION)

  # store spillover import offspring
  spilloverOffspring = dataCaseImport[DAY_OF_INFECTION > endTimePeriod,.(DAY_OF_INFECTION, NOTIFIED_INFECTOR, OFFSPRING) ]
 
  
  # store offsprings
  currentInc = dataCaseImport[DAY_OF_INFECTION %in% currentParam$time]
  
  # generate community cases by day of infection 
  dataCasePrevGen = dataCaseImport[DAY_OF_INFECTION %in% currentParam$time]
  
  # loop each case through 21 generations
  for(gen in 1:22){
    
    dataCaseComm = melt(dataCasePrevGen[,.(DAY_OF_INFECTION,
                                           NOTIFIED_OFFSPRING_NOTIFIED_INFECTOR,
                                           NOTIFIED_OFFSPRING_MISSED_INFECTOR,
                                           MISSED_OFFSPRING_NOTIFIED_INFECTOR,
                                           MISSED_OFFSPRING_MISSED_INFECTOR)], 
                        id = c('DAY_OF_INFECTION'))
    
    setnames(dataCaseComm, c('DAY_OF_INFECTION_INFECTOR', 'NOTIFIED_INFECTOR', 'INFECTOR'))
    dataCaseComm = dataCaseComm[!is.na(INFECTOR)] 
    dataCaseComm[NOTIFIED_INFECTOR %in% c('NOTIFIED_OFFSPRING_NOTIFIED_INFECTOR', 'NOTIFIED_OFFSPRING_MISSED_INFECTOR'), 
                 NOTIFIED_INFECTOR := 'Y']
    dataCaseComm[NOTIFIED_INFECTOR %in% c('MISSED_OFFSPRING_NOTIFIED_INFECTOR', 'MISSED_OFFSPRING_MISSED_INFECTOR'), 
                 NOTIFIED_INFECTOR := 'N']
    
    dataCaseComm = dataCaseComm[, sum(INFECTOR), by = .(DAY_OF_INFECTION_INFECTOR, NOTIFIED_INFECTOR)]
    setnames(dataCaseComm, c('DAY_OF_INFECTION_INFECTOR', 'NOTIFIED_INFECTOR', 'INFECTOR'))
    
    dataCaseComm = dataCaseComm[rep(seq_len(nrow(dataCaseComm)), each = 22), ]
    
    dataCaseComm[, `:=` (DAY_OF_INFECTION = rep(c(0:21), times = .N/22) + DAY_OF_INFECTION_INFECTOR,
                         PROB_AT_LARGE    = 1,
                         GEN_INTERVAL     = rep(distGen[, GEN_INTERVAL], times = .N/22))]
      
    dataCaseComm[NOTIFIED_INFECTOR == 'Y', PROB_AT_LARGE := rep(distIsolate[,PROB_AT_LARGE], times = .N/22)]
    dataCaseComm[, OFFSPRING := INFECTOR*PROB_AT_LARGE*GEN_INTERVAL*currentParam$param[1]]
    
    dataCaseComm = dataCaseComm[, .(DAY_OF_INFECTION, NOTIFIED_INFECTOR, OFFSPRING)]
    dataCaseComm = dataCaseComm[, sum(OFFSPRING), by = .(DAY_OF_INFECTION, NOTIFIED_INFECTOR)]
    setnames(dataCaseComm, c('DAY_OF_INFECTION', 'NOTIFIED_INFECTOR', 'OFFSPRING'))
    
    spilloverOffspring = rbind(spilloverOffspring, dataCaseComm[DAY_OF_INFECTION > endTimePeriod])
    dataCaseComm = dataCaseComm[DAY_OF_INFECTION %in% currentParam$time]
      
    dataCaseComm[NOTIFIED_INFECTOR =="Y", 
                 `:=` (NOTIFIED_OFFSPRING_NOTIFIED_INFECTOR = OFFSPRING*currentParam$param[2],
                       MISSED_OFFSPRING_NOTIFIED_INFECTOR   = OFFSPRING*(1-currentParam$param[2]))]
      
    dataCaseComm[NOTIFIED_INFECTOR =="N", 
                 `:=` (NOTIFIED_OFFSPRING_MISSED_INFECTOR = OFFSPRING*currentParam$param[3],
                       MISSED_OFFSPRING_MISSED_INFECTOR   = OFFSPRING*(1-currentParam$param[3]))]
      
    #setorder(dataCaseComm, -NOTIFIED_INFECTOR, DAY_OF_INFECTION)
    
    dataCasePrevGen = dataCaseComm
    
    currentInc = rbindlist(list(currentInc, dataCaseComm),
                           use.names = T, fill = T)
    
  }
  
  currentInc[is.na(currentInc)] = 0
  currentInc = currentInc[order(NOTIFIED_INFECTOR, DAY_OF_INFECTION)]
  
  # tabulate spillover offspring
  spilloverOffspring = spilloverOffspring[,sum(OFFSPRING), by = .(DAY_OF_INFECTION,NOTIFIED_INFECTOR)]
  spilloverOffspring[, NOTIFIED_INFECTOR := as.character(NOTIFIED_INFECTOR)]
  setnames(spilloverOffspring, c('DAY_OF_INFECTION', 'NOTIFIED_INFECTOR', 'OFFSPRING'))
  setorder(spilloverOffspring, -NOTIFIED_INFECTOR, DAY_OF_INFECTION)
  
  # tabulate all infection
  currentIncInfection = currentInc[, .(DAY_OF_INFECTION, NOTIFIED_OFFSPRING_MISSED_INFECTOR, NOTIFIED_OFFSPRING_NOTIFIED_INFECTOR,
                                       MISSED_OFFSPRING_MISSED_INFECTOR, MISSED_OFFSPRING_NOTIFIED_INFECTOR)]
  currentIncInfection = currentIncInfection[, .(sum(NOTIFIED_OFFSPRING_MISSED_INFECTOR), sum(NOTIFIED_OFFSPRING_NOTIFIED_INFECTOR),
                                                sum(MISSED_OFFSPRING_MISSED_INFECTOR), sum(MISSED_OFFSPRING_NOTIFIED_INFECTOR)),
                                      by = .(DAY_OF_INFECTION)]
  setnames(currentIncInfection, c('DAY_OF_INFECTION', 'NOTIFIED_COMM_UNLINKED', 'NOTIFIED_COMM_LINKED',
                                  'MISSED_COMM_UNLINKED', 'MISSED_COMM_LINKED'))
  
  # tabulate isolated infections
  currentIncIsolate = currentIncInfection[,.(DAY_OF_INFECTION, NOTIFIED_COMM_UNLINKED, NOTIFIED_COMM_LINKED)]
  setnames(currentIncIsolate, c('TIME', 'NOTIFIED_COMM_UNLINKED', 'NOTIFIED_COMM_LINKED'))
  
  # convert day of infection to day of isolation
  currentIncIsolate = currentIncIsolate[rep(seq_len(nrow(currentIncIsolate)), each = 22), ]
  currentIncIsolate[, DAY_SINCE_INFECTION := rep(0:21, times = .N/22)]
  currentIncIsolate[, PROB_ISOLATE := rep(distIsolate[, PROB_ISOLATE], times = .N/22)]
  
  currentIncIsolate[, `:=` (NOTIFIED_COMM_UNLINKED = NOTIFIED_COMM_UNLINKED*PROB_ISOLATE,
                             NOTIFIED_COMM_LINKED = NOTIFIED_COMM_LINKED*PROB_ISOLATE)]
  currentIncIsolate[, `:=` (TIME = TIME + DAY_SINCE_INFECTION,
                             DAY_SINCE_INFECTION = NULL,
                             PROB_ISOLATE = NULL)]
  
  # add spillover date isolate
  currentIncIsolate = rbind(currentIncIsolate, dataSpilloverDateIsolate)
  
  currentIncIsolate = currentIncIsolate[, .(sum(NOTIFIED_COMM_UNLINKED), sum(NOTIFIED_COMM_LINKED)),
                                          by = .(TIME)]
  
  setnames(currentIncIsolate, c('TIME', 'NOTIFIED_COMM_UNLINKED', 'NOTIFIED_COMM_LINKED'))
  
  # spillover isolation
  spilloverDateIsolate = currentIncIsolate[TIME > endTimePeriod]
  
  currentIncIsolate = currentIncIsolate[TIME <=  endTimePeriod,]
  
  currentInc = list(currentIncIsolate = currentIncIsolate,
                    currentIncInfection = currentIncInfection,
                    spilloverOffspring = spilloverOffspring,
                    spilloverDateIsolate = spilloverDateIsolate)
  
  return(currentInc)
  
}

calculateLogLik <- function(dataInc, currentInc, lenTime){
  
  LL = sum(sapply(1:lenTime, 
                  function(x) dpois(dataInc$NOTIFIED_COMM_UNLINKED[x], currentInc$NOTIFIED_COMM_UNLINKED[x], log = T)),
           sapply(1:lenTime, 
                  function(x) dpois(dataInc$NOTIFIED_COMM_LINKED[x], currentInc$NOTIFIED_COMM_LINKED[x], log = T))
  )
  
  return(sum(LL))
  
}


mh <- function(oldParam,newParam, 
               dataInc, oldInc,
               dataCaseImportNotified,dataIncImport, dataSpilloverOffspring, dataSpilloverDateIsolate)
{
  reject = FALSE
  count	= 0

  if(any(newParam$param < 0)) reject =TRUE
  if(any(newParam$param[c(1)] > 5 )) reject =TRUE #, 5,  9, 13, 17
  if(any(newParam$param[c(2)] > 1 )) reject =TRUE #, 6, 10, 14, 18
  if(any(newParam$param[c(3)] > 1 )) reject =TRUE #, 7, 11, 15, 19
  if(any(newParam$param[c(4)] > 20)) reject =TRUE #, 8, 12, 16, 20

  if(!reject){

    # simulate daily incidence
    currentInc = simCommInc(dataCaseImportNotified, dataIncImport, dataSpilloverOffspring, dataSpilloverDateIsolate,
                            newParam, distGen, distIsolate, distTravel)
    
    newParam$LL = calculateLogLik(dataInc, currentInc$currentIncIsolate, newParam$lenTime)
    differenceLL = newParam$LL-oldParam$LL 
    
    if(log(runif(1))>differenceLL){
      reject=TRUE
    } else{
      count	= 1
    }

    
  }
  
  if(reject) return(list(oldParam,
                         count,
                         oldInc))
  
  return(list(newParam,
              count,
              currentInc))
  
}
